-- MySQL Script generated by MySQL Workbench
-- mar 05 mar 2019 16:54:01 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PTA18-19
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PTA18-19` ;

-- -----------------------------------------------------
-- Schema PTA18-19
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PTA18-19` DEFAULT CHARACTER SET utf8 ;
USE `PTA18-19` ;

-- -----------------------------------------------------
-- Table `PTA18-19`.`Irakasleak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PTA18-19`.`Irakasleak` ;

CREATE TABLE IF NOT EXISTS `PTA18-19`.`Irakasleak` (
  `idIrakasleak` INT NOT NULL AUTO_INCREMENT,
  `izena` VARCHAR(45) NOT NULL,
  `abizenak` VARCHAR(45) NOT NULL,
  `datuak` VARCHAR(45) NULL,
  `jaiotzedata` VARCHAR(45) NOT NULL,
  `kokapena` VARCHAR(45) NOT NULL,
  `dirua` FLOAT NOT NULL,
  `erabiltzaile_izena` VARCHAR(45) NOT NULL,
  `pasahitza` VARCHAR(45) NOT NULL,
  `telefono_zenbakia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIrakasleak`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PTA18-19`.`Ikasleak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PTA18-19`.`Ikasleak` ;

CREATE TABLE IF NOT EXISTS `PTA18-19`.`Ikasleak` (
  `idIkasleak` INT NOT NULL AUTO_INCREMENT,
  `izena` VARCHAR(45) NOT NULL,
  `abizenak` VARCHAR(45) NOT NULL,
  `datuak` VARCHAR(45) NULL,
  `jaiotzedata` VARCHAR(45) NOT NULL,
  `kokapena` VARCHAR(45) NOT NULL,
  `erabiltzaile_izena` VARCHAR(45) NOT NULL,
  `pasahitza` VARCHAR(45) NOT NULL,
  `telefono_zenbakia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIkasleak`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PTA18-19`.`Ikasgaiak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PTA18-19`.`Ikasgaiak` ;

CREATE TABLE IF NOT EXISTS `PTA18-19`.`Ikasgaiak` (
  `idIkasgaiak` INT NOT NULL AUTO_INCREMENT,
  `izena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIkasgaiak`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PTA18-19`.`Mailak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PTA18-19`.`Mailak` ;

CREATE TABLE IF NOT EXISTS `PTA18-19`.`Mailak` (
  `idMailak` INT NOT NULL AUTO_INCREMENT,
  `izena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMailak`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PTA18-19`.`Ordutegiak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PTA18-19`.`Ordutegiak` ;

CREATE TABLE IF NOT EXISTS `PTA18-19`.`Ordutegiak` (
  `idOrdutegia` INT NOT NULL AUTO_INCREMENT,
  `eguna` INT NOT NULL,
  `denboratartea` INT NOT NULL,
  PRIMARY KEY (`idOrdutegia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PTA18-19`.`Klaseak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PTA18-19`.`Klaseak` ;

CREATE TABLE IF NOT EXISTS `PTA18-19`.`Klaseak` (
  `idKlaseak` INT NOT NULL AUTO_INCREMENT,
  `Irakasleak_idIrakasleak` INT NOT NULL,
  `Ikasgaiak_idIkasgaiak` INT NOT NULL,
  `Mailak_idMailak` INT NOT NULL,
  `Ordutegiak_idOrdutegia` INT NOT NULL,
  PRIMARY KEY (`idKlaseak`),
  INDEX `fk_Klaseak_Ikasgaiak1_idx` (`Ikasgaiak_idIkasgaiak` ASC),
  INDEX `fk_Klaseak_Mailak1_idx` (`Mailak_idMailak` ASC),
  INDEX `fk_Klaseak_Ordutegiak1_idx` (`Ordutegiak_idOrdutegia` ASC),
  INDEX `fk_Klaseak_Irakasleak_idx` (`Irakasleak_idIrakasleak` ASC),
  CONSTRAINT `fk_Klaseak_Irakasleak`
    FOREIGN KEY (`Irakasleak_idIrakasleak`)
    REFERENCES `PTA18-19`.`Irakasleak` (`idIrakasleak`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Klaseak_Ikasgaiak1`
    FOREIGN KEY (`Ikasgaiak_idIkasgaiak`)
    REFERENCES `PTA18-19`.`Ikasgaiak` (`idIkasgaiak`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Klaseak_Mailak1`
    FOREIGN KEY (`Mailak_idMailak`)
    REFERENCES `PTA18-19`.`Mailak` (`idMailak`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Klaseak_Ordutegiak1`
    FOREIGN KEY (`Ordutegiak_idOrdutegia`)
    REFERENCES `PTA18-19`.`Ordutegiak` (`idOrdutegia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PTA18-19`.`Eskariak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PTA18-19`.`Eskariak` ;

CREATE TABLE IF NOT EXISTS `PTA18-19`.`Eskariak` (
  `idEskariak` INT NOT NULL AUTO_INCREMENT,
  `Klaseak_idKlaseak` INT NOT NULL,
  `Ikasleak_idIkasleak` INT NOT NULL,
  PRIMARY KEY (`idEskariak`),
  INDEX `fk_Eskariak_Klaseak1_idx` (`Klaseak_idKlaseak` ASC),
  INDEX `fk_Eskariak_Ikasleak1_idx` (`Ikasleak_idIkasleak` ASC),
  CONSTRAINT `fk_Eskariak_Klaseak1`
    FOREIGN KEY (`Klaseak_idKlaseak`)
    REFERENCES `PTA18-19`.`Klaseak` (`idKlaseak`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Eskariak_Ikasleak1`
    FOREIGN KEY (`Ikasleak_idIkasleak`)
    REFERENCES `PTA18-19`.`Ikasleak` (`idIkasleak`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

GRANT ALL ON `PTA18-19`.* TO 'ikaslea';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `PTA18-19`.`Irakasleak`
-- -----------------------------------------------------
START TRANSACTION;
USE `PTA18-19`;
INSERT INTO `PTA18-19`.`Irakasleak` (`idIrakasleak`, `izena`, `abizenak`, `datuak`, `jaiotzedata`, `kokapena`, `dirua`, `erabiltzaile_izena`, `pasahitza`, `telefono_zenbakia`) VALUES (1, 'sandra', 'martinez arroyo', '', '01/10/1996', 'Alegria-Dulantzi', 12, 'smartinez112', 'smartinez112', '616995056');
INSERT INTO `PTA18-19`.`Irakasleak` (`idIrakasleak`, `izena`, `abizenak`, `datuak`, `jaiotzedata`, `kokapena`, `dirua`, `erabiltzaile_izena`, `pasahitza`, `telefono_zenbakia`) VALUES (2, 'inhar', 'yeregui arrieta', '', '20/05/1996', 'Zumaia', 15, 'iyeregui004', 'iyeregui004', '678678678');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PTA18-19`.`Ikasleak`
-- -----------------------------------------------------
START TRANSACTION;
USE `PTA18-19`;
INSERT INTO `PTA18-19`.`Ikasleak` (`idIkasleak`, `izena`, `abizenak`, `datuak`, `jaiotzedata`, `kokapena`, `erabiltzaile_izena`, `pasahitza`, `telefono_zenbakia`) VALUES (1, 'ane', 'sanz rekalde', '', '21/01/1996', 'Euba', 'asanz060', 'asanz060', '666666666');
INSERT INTO `PTA18-19`.`Ikasleak` (`idIkasleak`, `izena`, `abizenak`, `datuak`, `jaiotzedata`, `kokapena`, `erabiltzaile_izena`, `pasahitza`, `telefono_zenbakia`) VALUES (2, 'miren', 'bacete martinez', '', '02/09/1996', 'Vitoria-Gasteiz', 'mbacete001', 'mbacete001', '654654654');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PTA18-19`.`Ikasgaiak`
-- -----------------------------------------------------
START TRANSACTION;
USE `PTA18-19`;
INSERT INTO `PTA18-19`.`Ikasgaiak` (`idIkasgaiak`, `izena`) VALUES (1, 'Matematika');
INSERT INTO `PTA18-19`.`Ikasgaiak` (`idIkasgaiak`, `izena`) VALUES (2, 'Euskera');
INSERT INTO `PTA18-19`.`Ikasgaiak` (`idIkasgaiak`, `izena`) VALUES (3, 'Fisika');
INSERT INTO `PTA18-19`.`Ikasgaiak` (`idIkasgaiak`, `izena`) VALUES (4, 'Kimika');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PTA18-19`.`Mailak`
-- -----------------------------------------------------
START TRANSACTION;
USE `PTA18-19`;
INSERT INTO `PTA18-19`.`Mailak` (`idMailak`, `izena`) VALUES (1, 'LH');
INSERT INTO `PTA18-19`.`Mailak` (`idMailak`, `izena`) VALUES (2, 'DBH');
INSERT INTO `PTA18-19`.`Mailak` (`idMailak`, `izena`) VALUES (3, 'Batxillergoa');
INSERT INTO `PTA18-19`.`Mailak` (`idMailak`, `izena`) VALUES (4, 'Unibertsitatea');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PTA18-19`.`Ordutegiak`
-- -----------------------------------------------------
START TRANSACTION;
USE `PTA18-19`;
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (1, 1, 1);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (2, 1, 2);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (3, 1, 3);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (4, 2, 1);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (5, 2, 2);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (6, 2, 3);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (7, 3, 1);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (8, 3, 2);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (9, 3, 3);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (10, 4, 1);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (11, 4, 2);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (12, 4, 3);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (13 , 5, 1);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (14, 5, 2);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (15, 5, 3);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (16, 6, 1);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (17, 6, 2);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (18, 6, 3);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (19, 7, 1);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (20 , 7, 2);
INSERT INTO `PTA18-19`.`Ordutegiak` (`idOrdutegia`, `eguna`, `denboratartea`) VALUES (21, 7, 3);

COMMIT;

